// LOCALHOST
### Get all contacts
GET http://localhost:3001/contacts


### Get contact by id
GET http://localhost:3001/contacts/622023f642f9ab4cd6e060b3


### Create contact
POST http://localhost:3001/contacts 
content-type: application/json

{
  "firstName": "Tony",
  "lastName": "Stark",
  "email": "tony@starkindustries.com",
  "favoriteColor": "Hot Rod Red",
  "birthday": "1970-05-29"
}


### PUT contact
PUT http://localhost:3001/contacts/682ea1909fa090a260bd02fe
content-type: application/json

{
  "firstName": "Anthony",
  "lastName": "Stark",
  "email": "ironman@avengers.com",
  "favoriteColor": "Red and Gold",
  "birthday": "1970-05-29"
}
### DELETE contact
DELETE http://localhost:3001/contacts/6220b775099269ff7b31ceab 

// PRODUCTION Deploy
### Get all contacts
GET https://cse341-instructor.herokuapp.com/contacts


### Get contact by id
GET https://cse341-instructor.herokuapp.com/contacts/682ea1909fa090a260bd02fe


### Create contact
POST https://cse341-instructor.herokuapp.com/contacts 
content-type: application/json

{
    "firstName":"Ashley",
    "lastName":"Weaver",
    "email":"aWeaver@test.com",
    "favoriteColor":"Brown",
    "birthday":"06/19/2000"
}


### PUT contact
PUT https://cse341-instructor.herokuapp.com/contacts/6220bcb39cd507e920c75a0b
content-type: application/json

{
    "firstName":"Sarah",
    "lastName":"Birch",
    "email":"sarahB@gmail.com",
    "favoriteColor":"Yellow",
    "birthday":"06/12/20"
}


### DELETE contact
DELETE https://cse341-instructor.herokuapp.com/contacts/6220e34083149913680f9a64